name: Tests

on:
    pull_request:
    push:
        branches:
            - main
            - master
            - dev

jobs:
    test:
        name: Running unit tests
        runs-on: ${{ matrix.os }}
        strategy:
              matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
                  deno:
                      [1.x, "1.8.2", canary, ~1.7, e7b7129b7a92b7500ded88f8f5baa25a7f59e56e]
        steps:
            - name: Actions Setup
              uses: actions/checkout@v2
            - name: Use Deno ${{ matrix.deno-version }}
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - name: Test Deno
              run: deno run https://deno.land/std/examples/welcome.ts
            - name: Test `deno install`
              run: |
                  deno install --allow-net -n deno_curl https://deno.land/std/examples/curl.ts
                  deno_curl https://deno.land/std/examples/curl.ts
            - name: Test
              run: deno test -A
